### ISSUE TITLE
Style for urls in summary

### ISSUE THREAD

**Issue by apyrgio** [apyrgio/synnefo#155]
In the summary of table rows, we can now have urls. These urls have almost the same color with the rest of the text, so they pass unnoticeable.

Change the style of these urls in order to stand out.

**Comment by olgabrani** [comment]
We need to find a default link color different from text color.
This default color will apply both to urls in the summary of table rows and to the links in the details page.
For the moment, I chose one (#9ed34d) that will make all links stand out, but its value and its hover state are open to discussion.
