### ISSUE TITLE
Diagrams for various items

### ISSUE THREAD

**Issue by athinab** [apyrgio/synnefo#16]
Add the ability to generate diagrams for stuff like number of users, number of VMs. The diagrams should be able to represent a timeline, e.g. a graph of activated users from 1/1/2013 as well as pie charts, e.g. number of VMs and their categories (started, shutdown, etc.)

**Comment by athinab** [comment]
**Possible Charts:**
Below there are some (maybe many :P) ideas regarding the information that we could visualize and the kind of charts that we could use in each case.

Note that we need to verify if the relative data are available.

# 

**Accounts state (active, inactive, pending moderation, pending verification)**
- [ ] Pie chart maybe with a drilldown of providers
- [ ] Timeline of active accounts

# 

**VMs status (stopped, started)**
- [ ] Pie chart

# 

**Suspended VMs**
- [ ] Timeline

# 

**Available IPs**
- [ ] Pie chart
- [ ] Timeline
  In this case the pie and the timeline maybe should be combined in one diagram

# 

**Drained Clusters**
- [ ] Timeline

# 

**Users with zero resources in use**
- [ ] Pie chart with users with and without resources

# 

**VMs per memory/disk**
- [ ] Column chart that shows the number of vms per resource (memory, disk) in a monthly base.
  For this chart what kind of value could we use?
  Max value? Average?

# 

**Free/Used CPUs/Memory/Disk**
- [ ] Pie chart
  For CPU drilldown to pie chart with slices active and virtual (?)
  For disk drilldown to pie chart with slices drbd and archipelagos
- [ ] Timeline (type: area)
  Combined in a single diagram per type of resource

# 

**Type of disk in use**
- [ ] Pie chart with slices drbd, archipelagos (included to charts above) 
- [ ] Timeline of archipelagos. Could be area witwo areas (lines): archipelagos and total

# 

**Projects state**
- [ ] Pie chart accepted/pending/denied.
  Could have a drilldown pie chart with slices modified, not-modified or expired, new.

# 

**Images/OSs**
tba

**Comment by athinab** [comment]
Will it be useful to have a chart with information about KSM?

**Comment by apyrgio** [comment]
- [ ] Reconsider colors for each chart.
- [ ] Column width for charts.
- [ ] The chart's width may be more than the div's width.

**Comment by apyrgio** [comment]
Also, given that the API url for stats may not be in the same node as the admin tool, we will have a problem with [same-origin policy](https://en.wikipedia.org/wiki/Same-origin_policy) for Javascript.

Unless we use JSON-P, we have two alternatives:
a) Make the call from the admin application
b) Instruct the server to proxy the request.

The first is preferable, but we will talk with psomas.

**Comment by apyrgio** [comment]
The above has been solved, the only issue is that currently we have a problem with the password salt for the cyclades stats.

**Comment by apyrgio** [comment]
The issue with password salt has been resolved. The last issue that we had and is also resolved (albeit not nicely) is that in order to get stats for images, we use raw SQL queries which do not pass from the database router. This resulted in hitting the default database, which by default was invalid.

The way we circumvented that by setting the cyclades database as default. However, we need to find a better way.

**Comment by apyrgio** [comment]
An addition to the above is that we have to migrate from Highcharts to C3 for licensing issues.

**Comment by athinab** [comment]
The migration has been successful.

**Comment by athinab** [comment]
The issue now contains only proposals for new diagrams. We have decided instead to implement the requests from our helpdesk and admin team and ditch the above proposals.
