### ISSUE TITLE
Missing flag in volumes

### ISSUE THREAD

**Issue by apyrgio** [apyrgio/synnefo#174]
In VMs there is Deleted and Destroyed. Currently, volumes only have Destroyed. See if there is a deleted too.

**Comment by olgabrani** [comment]
There are 3 'Deleted' badges for the volume shown in the screenshot:
![screen shot 2014-07-15 at 11 11 32](https://cloud.githubusercontent.com/assets/2444615/3582136/aa354d58-0bf7-11e4-9bdd-60d6f77b1f09.png)
