### ISSUE TITLE
Add quotas, projects and account details in user page

### ISSUE THREAD

**Issue by athinab** [apyrgio/synnefo#19]
In the single user page we need to add any detail that we have. We need different sections for quotas, projects and account, similar in style with the VM and network sections.

Also, add the necessary action buttons for the above.

**Comment by apyrgio** [comment]
My proposal is the following:

We keep everything from the VM section and down as is. These sections are enough for our needs. What we need to do is to improve the astakos section.

We will replace the current section (where the user name and uuid are shown) with a section similar to the VM section.

This section will have the following tabs:

| Details | Quotas | Providers |
| --- | --- | --- |
| Name John Doe | Storage space Total/Base/Free | Available providers: |
| UUID: 3260616f4e5f | System Disk | Enabled providers: |
| State: Active/Inactive/... | Total CPUs |  |
|  | CPUs |  |
|  | Total Ram |  |
|  | RAM |  |
|  | ... |  |

Under this section, we will have the following actions: `Activate`, `Deactivate`, ..., `Contact`, `Resend activation mail`...

Next, we will have a list with projects that will be just like the VM list. Each project will have the following tabs:

| Details | Resources | Members |
| --- | --- | --- |
| Name: | Storage Space: per user/total | Participants: max/current |
| Owner: link to owner | System Disk: | Join policy: |
| Description: | CPUs: | Leave policy: |
| State | RAM: | User is: Owner/Accepted/Pending/... |
| Started date: | VMs: |  |
| End date: | Private Networks: |  |
|  | Floating IPs: |  |

and the project actions will be: `Approve project`, `Deny project`.

**Comment by athinab** [comment]
**Proposed additions for account section:**
- Dates regarding the account states.
  Particularly dates that indicate when a user was:
  - signed up
  - verified
  - moderated (accepted, rejected)
  - deactivated
  - logged in for the last time
- Username/ID that enabled providers use.
  For example eppn of Shibboleth provider.
- Action for e-mail modification.

**Comment by apyrgio** [comment]
**Proposed additions for the project section:**

The "Owner" field can be the realname of the owner, as in the Projects page. However, we can create a link to the actual owner page in order to get more details.

**Comment by athinab** [comment]
**Proposed additions for the project section:**
- Role of the current user: owner, just member
- State of the project: pending, accepted, rejected
- State of membership: pending, accepted, rejected

**Comment by apyrgio** [comment]
A large number of the above has been implemented in 0f9c4a7. This issue can close and later adjustments can be made in future issues.
