### ISSUE TITLE
Errors (problematic links etc)

### ISSUE THREAD

**Issue by athinab** [apyrgio/synnefo#197]
- [x] 404 Page not found when I hit "/admin"
- [x] 504 Gateway Time-out when I hit:
  https://admin.demo.synnefo.org/user/826ea88e-25b3-4d73-9e81-f3a6521c5d04
- [x] Slow load for: https://admin.demo.synnefo.org/user/debbd63a-ac39-4b7f-afe8-f1953e599003

**Comment by apyrgio** [comment]
The issues have been resolved. If any new issue is reported, please reopen the ticket.

**Comment by Erethon** [comment]
404 Page not found when I hit: https://admin.demo.synnefo.org/ip/192.168.1.2
404 Page not found when I hit: https://admin.demo.synnefo.org/ip/192.168.0.8
404 Page not found when I hit: https://admin.demo.synnefo.org/ip/192.168.0.4

**Comment by apyrgio** [comment]
The problem is quite simple actually: there are more than one IPs with address "192.168.1.2"!
I'll handle it appropriately...

**Comment by apyrgio** [comment]
The above have been fixed. As always, if any new issue is reported, please reopen the ticket.
