### ISSUE TITLE
Save state in dataTables 

### ISSUE THREAD

**Issue by olgabrani** [apyrgio/synnefo#200]
One probably useful feature would be to enable state saving in tables.
There is a dataTable option
[stateSave](https://datatables.net/reference/option/stateSave)

According to the docs:
'Enable or disable state saving. When enabled aDataTables will storage state information such as pagination position, display length, filtering and sorting. When the end user reloads the page the table's state will be altered to match what they had previously set up.'

**Comment by athinab** [comment]
I agree, this is useful.
When we enable it, we need to integrate the custom filters, that we use. (They should keep their last value, just like the search field of datatables).

**Comment by apyrgio** [comment]
Fixed, aside from the last proposition which will not be implemented.
