### ISSUE TITLE
Show label info in tab panel

### ISSUE THREAD

**Issue by olgabrani** [apyrgio/synnefo#217]
Maybe we should include the labels' info in the content of the tab panel below each item in details view.
The information will be in two places but I think it would be easier for the user to have a more spherical view at a glance.
Moreover, the labels are usually considered to be **extra** info and probably info like the user's email etc are expected to be in the details tab panel as well.

**Comment by apyrgio** [comment]
That seems reasonable. I'll tag it for 0.16.
