### ISSUE TITLE
Wait until user stops typing in filter field before sending Ajax request

### ISSUE THREAD

**Issue by apyrgio** [apyrgio/synnefo#227]
Currently, each keypress is a separate Ajax request. We should improve this and do it like DataTables.

**Comment by apyrgio** [comment]
An associated feature with this is what happens when a user pastes something in the filter box. As of now, we don't send a request and we wait to press "Enter". Is this approach ok?

**Comment by apyrgio** [comment]
@AthinaB : The approach that we currently have works, right? What's left to close this issue?

**Comment by athinab** [comment]
We can close it.
