### ISSUE TITLE
Filter names

### ISSUE THREAD

**Issue by apyrgio** [apyrgio/synnefo#234]
In the table view, we have a filter list that has cryptic names for the associations of an item:
"HAS User", "OF Project", "IN Network" etc.

While typically correct, they encumber the page and require from the user to view them in a grammar context in order to understand them. A glimpse on the other hand will confuse him/her more.

I believe that we could do just as well by having an icon next to the filter name, to show that this filter will not search in the main item fields, but will fetch the associated items for the users query.

E.g. we are in a network view and there are two filters: Network and User.
We need an intuitive way to make the user understand that:
a) Searching in "Network" will filter the entries of the table,
b) Searching in "User" will filter the Users and then simply return the networks that belong to these users.

My proposal is to get rid of the "HAS", "OF", "IN" and use an elegant icon like [this](http://cdn.business2community.com/wp-content/uploads/2013/03/share_this_icon.png) that will convey our message.

**Comment by olgabrani** [comment]
I think we should leave the HAS/OF/IN as they are.
Once the admin user learns that "OF User" for example means: "search for Networks that belong to user" it will be easier for him/her to perform the search.
Maybe we should include a tooltip on label hover ?
Could each filter, apart from having a name, and a label have a help text as well?

**Comment by apyrgio** [comment]
> I think we should leave the HAS/OF/IN as they are.
> Once the admin user learns that "OF User" for example means: "search for Networks that belong to user" it will be easier for him/her to perform the search.

![okay...](http://digboston.com/wp-content/uploads/2012/06/okay.jpeg)

> Maybe we should include a tooltip on label hover ?
> Could each filter, apart from having a name, and a label have a help text as well?

It's doable. We could also add there info about searchable fields. However, this needs tweaking, which makes it more suited for 0.16-hotfix.

**Comment by olgabrani** [comment]
In da78db8 we added font-icons in filter labels. This possibly closes the issue.
