### ISSUE TITLE
DataTables processing indicator and large pagination

### ISSUE THREAD

**Issue by apyrgio** [apyrgio/synnefo#236]
The "Processing" indicator for a table appears in the middle of the table. This means that if the pagination is big, the user will probably not realize that a request is being processed.

Is it possible to move the "Processing" indicator someplace else? If not, then we don't have to bother.

**Comment by olgabrani** [comment]
Instead of moving the "Processing" indicator someplace else, we have added opacity:0.4 while the table is loading.
