### ISSUE TITLE
Clear all icon

### ISSUE THREAD

**Issue by apyrgio** [apyrgio/synnefo#237]
The "x" in the "Clear all icon should be on the right of the button and not on the left. I'm not sure if this is fixed however.

**Comment by athinab** [comment]
Why should the icon be on the right?
In common case the icon goes before text, especially when the icon is used to distinguish an item.
(This is associated with the fact that the user reads from left to the right and we want the user to see first the icon and get a glimpse of what kind of "karma" has the particular item or what kind of action a button performs.)

However, we can change it easily if we don't like there.
