### ISSUE TITLE
Do not keep the action highlighted in an empty modal

### ISSUE THREAD

**Issue by apyrgio** [apyrgio/synnefo#239]
In an action modal, if we have removed all items the action was referring to, then the action button should become gray.

**Comment by athinab** [comment]
For now, if the user removes all the items and then clicks the button that performs the action, a red sign appears next to the place where the data of the items are placed (if there are any). Also, on hover of this sign there are more info about the problem. This is a common approach to guide the user in forms.

Also, is consistent with the way that we represent errors that may appear in contact modal (like empty subject or body of e-mail). In this case the error sign goes next to the corresponding area.

**Comment by olgabrani** [comment]
Where is the message that was supposed to appear on error sign hover?
