### ISSUE TITLE
Remove stale files from admin

### ISSUE THREAD

**Issue by apyrgio** [apyrgio/synnefo#287]
There are files such as `Sorting icons.psd` that serve no purpose and should be removed. This issue is part of a larger issue, the #131 .

**Comment by athinab** [comment]
We can also remove demohighcharts.js, timelineData.js, temp-charts.js.

**Comment by athinab** [comment]
Present list of unnecessary **static** files:
- js directory:
  - charts_theme.js (remove url from charts.html)
  - datatables.bootstrap.js
  - demohighcharts.js
  - Highcharts_drilldown.src.js (remove url from charts.html)
  - highstock.src.js (remove url from charts.html)
  - jquery-2.0.3.js
  - temp-charts.js.
  - timelineData.js
- css directory:
  - ie.css (remove commented include from base.html)
  - print.css
  - theme1.css
- ccs/min directory:
  - icon-fonts.css
  - ie.css
  - print.css
- img directory: all
- sass directory:
  - ie.scss
  - print.scss
