### ISSUE TITLE
Add github-like back button

### ISSUE THREAD

**Issue by apyrgio** [apyrgio/synnefo#32]
Add a back button on the left of "Synnefo admin". This button should be similar to the back button that github has on the issues page.

**Comment by apyrgio** [comment]
We have a breadcrumb implementation on the works that should fix this issue.

**Comment by athinab** [comment]
Breadcrumb will not be implemented after all.

**Comment by athinab** [comment]
The sub-nav and navigation bar should provide the necessary logic for "Back" actions.
