### ISSUE TITLE
Service navigation bar: tabs

### ISSUE THREAD

**Issue by athinab** [apyrgio/synnefo#36]
The navigation bar should have the following tabs (and the relative pages):
- [x] Home
- [x] Users
- [x] VMs
- [x] Volumes
- [x] Networks
- [x] IPs
- [x] Projects
- [x] User groups
- [x] Authentication methods
- [x] Statistics (raw numbers)
- [ ] Utilization charts
- [ ] Timeline charts

Charts could be placed in a dropdown list with title "Charts". In this case, the options "Utilization" and "Timeline" will appear when the mouse hovers .

**Comment by athinab** [comment]
The above tabs are all in the navigation bar but, for now, some of them don't have the corresponding url.

Notes: 
- "Home" has been replaced from the header of the app, "Synnefo Admin Panel".
- Statistics and charts are part of the dropdown list "Reports".

**Comment by apyrgio** [comment]
As I see it, the navigation bar currently has the above tabs. So, can we close this?
