### ISSUE TITLE
Detail-templates: Buttons

### ISSUE THREAD

**Issue by athinab** [apyrgio/synnefo#37]
Add action-buttons to the pages/templates that represent the detailed info of each item.

**Comment by apyrgio** [comment]
These buttons are actually the same as in the `action_list_vertical.html` template. The only change is making them horizontal. Do we need something else too? A change in modals perhaps?

**Comment by apyrgio** [comment]
I have created a `feature-admin-details-actions` branch which has most of the server-side functionality implemented. The commit that you probably want to see is the 1be951833260abff4eae. Read the log and we can discuss about it when you're ready.
