### ISSUE TITLE
Summary info

### ISSUE THREAD

**Issue by athinab** [apyrgio/synnefo#4]
What to have in the summary info of each "model"?

**Comment by apyrgio** [comment]
Before writing about what will be included in the summary of each "model", we should note that the summary cannot be just a box that will list the most important information about the "model", as some of that information is already in the "model" list.

What we can do however is to have a "More..." button that will expand the list entry (maximum three lines) and will add some more fileds. Next to "More...", we can have a "Full" button that should go to the full description of the model.

Therefore, what we need to do to answer this question is to categorize the fields of the "Models" in Major and Significant, the latter being not as strong as the former.
