### ISSUE TITLE
Change the owner of VM

### ISSUE THREAD

**Issue by athinab** [apyrgio/synnefo#45]
In the VM index page there should be a "Change the owner" action that would transfer a VM from one owner to the other.

**Comment by apyrgio** [comment]
This change means that the actions must:
1. Accept input (in this case email, uuid etc.)
2. Query the server to asynchronously get the users that match the provided input.
3. Send the user id along with the action info.

**Comment by athinab** [comment]
Integrated in the issue apyrgio/synnefo#298
