### ISSUE TITLE
Astakos/Cyclades dates

### ISSUE THREAD

**Issue by athinab** [apyrgio/synnefo#5]
Which are the dates that astakos/cyclades handle? Which of them to keep in the summary?

**Comment by apyrgio** [comment]
# Astakos dates

Astakos dates can be divided in two categories, **User** dates and **Project** dates. Most of these dates are self-explanatory, so we will comment where necessary:

## User dates
- update_date: The last time the user model was updated (e.g. the token/password/name mail was activated)
- deactivated_at
- verified_at
- activation_sent
- moderated_at
- date_signed_terms

## Project dates
- start_date
- end_date
- create_date: When the project was created
- issue_date: When the project application was created
- response_date: When we responded to an application
- waive_date: When the user ended the project

# Cyclades dates

The cyclades dates can be divided in more categories. Namely, Cyclades handle **VMs**, **Networks**, **NetworkInterfaces**, **Backends**, **BackendNetworks** and **IPs**.

## VM dates
- created
- updated

## Network dates
- created
- updated
- deleted

## NetworkInterface dates
- created
- updated

## Backend dates
- updated

## BackendNetwork dates
- created
- updated

## IP dates
- created
- updated
- allocated_at
- released_at
