### ISSUE TITLE
List of users in contact modal

### ISSUE THREAD

**Issue by athinab** [apyrgio/synnefo#62]
The data of each user in the table of the modal should be included only once.

**Comment by athinab** [comment]
The main table that includes all items can have more then one item of the same user-account.

In order the admin-user to understand that he choose more then one time the same account I suggest to attach a tooltip in every row of the table in the modal.

The tooltip may have text such as: "You choose this account for the <item-name-1>,..., <item-name-n>". The tooltip will appear when the mouse hovers over a row.

**Comment by apyrgio** [comment]
I'm fine with that, as long as there is a grey, small italic text that informs the user that "Duplicate accounts have been detected".

Other than that, you will probably need to have the item-name in the extra JSON. Is it possible for now to use the provided item id?

**Comment by athinab** [comment]
Done and merged.
