### ISSUE TITLE
Split base projects from user-created projects

### ISSUE THREAD

**Issue by athinab** [apyrgio/synnefo#63]
The projects that the system creates for each account (base) should have a separated table or view or even should be displayed in a different url from the ones the users create.

Also, we should decide a name for each of the two categories.

Proposals:
- System Projects, Users Projects (indicates who created them)
- Base Projects, Custom Projects (indicates the type of them)

**Comment by apyrgio** [comment]
> Base Projects, Custom Projects (indicates the type of them)

How about: Base Projects, Public Projects?

**Comment by athinab** [comment]
The term "Public" is already used in projects.
There is a distinguish between private and public projects.
I am not sure what is the difference between private and public, though.
Maybe is related with the joining policy?

Check the text of the section "Join" in https://accounts.okeanos.grnet.gr/ui/projects.

**Comment by apyrgio** [comment]
Ok, let's settle with Base Quotas, Projects and see if the others will agree.
