### ISSUE TITLE
Projects table: Included data

### ISSUE THREAD

**Issue by athinab** [apyrgio/synnefo#64]
For the evaluation of a project activation request it will be useful to add in the table the following data:
- [x] Creation date in a column of the table. Should have sorting ability in this column, if possible.
- [x] Comments for review and a summary of resources in an easily seen place. In a column or inside summary area I think it will be fine.
- [ ] For this type of items, probably a common use case is the search by user email or name. So if we agree in that, we need to have these data in hidden (or maybe better in visible) columns for server-side search.

**Comment by apyrgio** [comment]
I'll log in this comment what we talked about the third option. There definitely should be a separate filter for user email / user name, and this is the first thing that we will do. However, it would be interesting if the global search box checked these filters as well.
