### ISSUE TITLE
Place "Details"/"Summary" somewhere more elegant

### ISSUE THREAD

**Issue by apyrgio** [apyrgio/synnefo#67]
In the items list, the "details"/"summary" buttons are repeated within the table. Given that this info never changes and that it takes space, we should move them elsewhere.

One suggestion is placing them in a dialog box, when the mouse hovers over a row.

**Comment by athinab** [comment]
For our first approach will place symbolic icons in the last column.
These will be visible when the user hovers the mouse over a row.
