### ISSUE TITLE
Actions metadata

### ISSUE THREAD

**Issue by athinab** [apyrgio/synnefo#86]
We now use karma and reversible to paint the elements that are related to an action.
But the colors that comes from these is not to the point.

We need to show with color-code if an action needs caution (warning = orange) or extra caution (dangerous = red) or is trivial and has no really effect on an item or has a positive impact on the item that is applied on.

Colors:
- Green
- Orange
- Red
- Blue

**Comment by athinab** [comment]
Suggestion:
caution-level: warning, dangerous, none
impact: neutral, positive, negative

Warning combined with neutral and negative will produce orange.
Dangerous combined with neutral and negative will produce red.
None combined with any impact will produce the default color of impact.
Any caution-level combined with positive impact will produce green.

The following list is more detailed:

warning+neutral, warning+negative -> orange
warning+positive  -> green (shouldn't get a combination of these probably?)
dangerous+neutral, dangerous +negative -> red
dangerous+positive -> green (shouldn't get a combination of these probably?)
none+neutral -> blue
none+positive -> green
none+negative -> orange (shouldn't get a combination of these probably?)

Does it make sense? Do you have another idea maybe?

**Comment by athinab** [comment]
Pending: The update of css rules in order to have a visual result.

**Comment by apyrgio** [comment]
At the time we have the following data attributes:
data-karma <- good, bad, neutral
data-caution <-  warning, dangerous, none (py property: caution_level)
